bindgen/src/gen_cs/mod.rs
bindgen/templates/wrapper.cs

Thanks for the great work!
We are using it successfully in Breez and it works very well. Only thing that we need is the ability to customize the namespace.
The reason is because we are using the same udl file for multiple languages and most languages use lower case for namespace/modules declarations so we can't make the namespace in the udl file suitable for c# case.
Therefore I added an optional configuration property to override the logic that composes the namespace today.

Add optional namespace configuration

---

Cargo.lock
bindgen/Cargo.toml
bindgen/src/gen_cs/mod.rs
bindgen/templates/CallbackInterfaceTemplate.cs
bindgen/templates/EnumTemplate.cs
bindgen/templates/ErrorTemplate.cs
bindgen/templates/ObjectTemplate.cs
bindgen/templates/RecordTemplate.cs
bindgen/templates/TopLevelFunctionTemplate.cs
bindgen/templates/macros.cs
bindgen/templates/wrapper.cs
dotnet-tests/UniffiCS.binding_tests/TestDocstring.cs
fixtures/Cargo.toml
fixtures/disposable/src/lib.rs
fixtures/src/lib.rs
test_bindings.sh

I accidentally merged PR train in the wrong order :sweat_smile: Docstring PR was supposed to be merged to 0.24.0 before merging 0.24.0 to main.
This code was already reviewed at: https://github.com/NordSecurity/uniffi-bindgen-cs/pull/10

Add docstring (reland)

---

Cargo.lock
README.md
bindgen/Cargo.toml
bindgen/src/gen_cs/mod.rs
bindgen/templates/wrapper.cs
dotnet-tests/UniffiCS.binding_tests/TestCallbacksFixture.cs
dotnet-tests/UniffiCS.binding_tests/TestChronological.cs
dotnet-tests/UniffiCS.binding_tests/TestCoverall.cs
dotnet-tests/UniffiCS.binding_tests/TestDocstring.cs
dotnet-tests/UniffiCS.binding_tests/TestRondpoint.cs
dotnet-tests/UniffiCS.binding_tests/TestTodoList.cs
dotnet-tests/UniffiCS.binding_tests/UniffiCS.binding_tests.csproj
dotnet-tests/UniffiCS/UniffiCS.csproj

The setting makes it a little bit easier to write new code, but it makes
it much harder to understand what dependencies the code has. Also,
relying on ImplicitUsings means that bindings consumers need to enable
this setting aswell.
Add missing imports for tests after disabling ImplicitUsings.
Fix import warning in wrapper.cs that appeared after turning off
ImplicitUsings.
Update README.md to reflect the actual Rust version requirement.
Update README.md with more accurate requirements for bindings consumers.

Turn off ImplicitUsings setting

---

Cargo.lock
bindgen/src/gen_cs/mod.rs
bindgen/src/gen_cs/primitives.rs
bindgen/templates/CustomTypeTemplate.cs
bindgen/templates/Float32Helper.cs
bindgen/templates/Float64Helper.cs
bindgen/templates/Int16Helper.cs
bindgen/templates/Int32Helper.cs
bindgen/templates/Int64Helper.cs
bindgen/templates/Int8Helper.cs
bindgen/templates/UInt16Helper.cs
bindgen/templates/UInt32Helper.cs
bindgen/templates/UInt64Helper.cs
bindgen/templates/UInt8Helper.cs
dotnet-tests/UniffiCS.binding_tests/TestCustomTypesBuiltin.cs
fixtures/Cargo.toml
fixtures/custom-types-builtin/Cargo.toml
fixtures/custom-types-builtin/build.rs
fixtures/custom-types-builtin/src/custom-types-builtin.udl
fixtures/custom-types-builtin/src/lib.rs
fixtures/src/lib.rs
test_bindings.sh

Lowercasing numeric types introduces a problem. In C# custom types are implemented with `using` directive, and the `using` directive expects and identifier on the right side of `=`. Lowercase numeric types are not identifiers, but rather reserved keywords. So its not possible to define a type alias using a lowercase numeric type as the underlying type. To use numeric types as the underlying type, the uppercase system type counterparts must be used
To generate correct code for custom types, create new filter `type_name_custom`, that formats these types in their respective system type counterparts.

Lowercase the numeric types

---

bindgen/src/lib.rs

Instead of implementing mutually exclusive and required options manually, this commit uses native Clap facilities.

bindgen: Use clap for option dependencies

---

Cargo.lock
bindgen/src/gen_cs/mod.rs
bindgen/templates/Types.cs
dotnet-tests/UniffiCS.binding_tests/TestBytesType.cs
dotnet-tests/UniffiCS.binding_tests/TestCoverall.cs
fixtures/Cargo.toml
fixtures/bytes-type/Cargo.toml
fixtures/bytes-type/build.rs
fixtures/bytes-type/src/bytes_type.udl
fixtures/bytes-type/src/lib.rs
fixtures/src/lib.rs

`Type::Bytes` produces incorrect code in the following situations:
- `u8` is not referenced anywhere else in the definition file. This causes undefined symbol `FfiConverterUint8`.
- `Vec<u8>` is referenced somewhere in the definition file. This causes duplicate symbol definition for `FfiConverterSequenceUint8`.
To fix this, replace `Type::Bytes` with `Type::Sequence<u8>` in known types set before rendering `Type.cs`. This ensures that both FFI converters `FfiConverterSequenceUInt8` and `FfiConverterUInt8` will be rendered exactly once in `Types.cs`.
Fixes #49.

Fix bytes type

---

bindgen/src/gen_cs/formatting.rs
bindgen/src/lib.rs

In Rust, command exit status has to be handled manually. Not handling exit status would cause the generator to generate invalid code when `dotnet` is installed, but `csharpier` is not installed.
Switch from using `dotnet csharpier` to using `dotnet-csharpier`. The former produces really verbose output by `dotnet` when `csharpier` is not installed or dotnet tools directory is not in PATH, while the latter returns a neat `command not found` error if CSharpier is not yet installed.

Fix error handling for command `dotnet csharpier`

---

README.md

Documenting that enum variants having the same name as their member type causes an C# error in name resolution.

Update README.md with Known Limitations section

---

bindgen/src/gen_cs/mod.rs
bindgen/templates/CallbackInterfaceTemplate.cs
bindgen/templates/CustomTypeTemplate.cs
bindgen/templates/EnumTemplate.cs
bindgen/templates/ErrorTemplate.cs
bindgen/templates/Helpers.cs
bindgen/templates/ObjectRuntime.cs
bindgen/templates/ObjectTemplate.cs
bindgen/templates/RecordTemplate.cs
bindgen/templates/wrapper.cs
docs/CONFIGURATION.md

Access modifier may be configured via `access_modifier` configuration value.
Closes https://github.com/NordSecurity/uniffi-bindgen-cs/issues/23

Change default access modifier to internal

---

dotnet-tests/UniffiCS.BindingTests/TestChronological.cs

DateTime always defaults to local time and needs to be explicitly converted to UTC.
The tests fail if the system timezone is not set to UTC. Because GitHub Actions use UTC by default this was not caught by CI.
I don't quite understand how DateTime conversion works. To me it looks like [TimeStampHelper.cs](https://github.com/NordSecurity/uniffi-bindgen-cs/blob/bebce29f8b3106dde014d5f0afd0b25526d7eefd/bindgen/templates/TimestampHelper.cs) assumes that passed DateTime values are always UTC, which is not the case.
The current implementation might not be sufficient.

fix: test using utc time

---

bindgen/templates/RecordTemplate.cs

Before this change, field-style `/// <summary>` docs were emitted on the *parameters* of the record's primary constructor. But this is invalid C# syntax.
Docs on record properties that are defined via primary constructor parameters need to be written as parameter docs on the primary constructor.
```cs
/// <param name="saplingRelativeSize">
/// Some doc
/// </param>
internal record AccountOptimizationSettings (
float @saplingRelativeSize
) {
}
```
```cs
internal record AccountOptimizationSettings(
/// <summary>
/// A non-negative number that will serve as the numerator when calculating the % of the shielded balance
/// that should be maintained the sapling pool.
/// The denominator is the sum of all shielded pool relative size fields.
/// </summary>
float @saplingRelativeSize,
) { }
``` …

Fix xml doc generation for fields in a record

---

CHANGELOG.md
bindgen/templates/CallbackInterfaceRuntime.cs
dotnet-tests/UniffiCS.BindingTests/TestCallbacksFixture.cs
dotnet-tests/UniffiCS.BindingTests/TestNullToEmptyString.cs
generate_bindings.sh

Alternative to #89 and #88, this is the simplest solution, assigning unrelated ID for the same callback object. I like the simplicity of this, but in my mind it may be difficult to debug callback issues if callback ID is completely unrelated for the same callback. But maybe I'm overthinking this?

Fix short lived callback lifetimes

---

CHANGELOG.md
Cargo.lock
README.md
bindgen/Cargo.toml

Fixed links in CHANGELOG.md. Seems like Github links to MR with `#XX`. To link with issue, full markdown link form should be used. 
E.g. link with MR (there was no issue created): `Fix xml doc generation for fields in a record (#87)`
E.g. link with issue: `**IMPORTANT**: Fix short-lived callback lifetimes [#79](https://github.com/NordSecurity/uniffi-bindgen-cs/issues/79)`

Bump v0.8.3+v0.25.0

---

Cargo.lock
bindgen/templates/RecordTemplate.cs
dotnet-tests/UniffiCS.BindingTests/TestIssue75.cs
dotnet-tests/UniffiCS.BindingTests/TestIssue76.cs
fixtures/Cargo.toml
fixtures/regressions/issue-75/Cargo.toml
fixtures/regressions/issue-75/README.md
fixtures/regressions/issue-75/src/lib.rs
fixtures/src/lib.rs

Fixes https://github.com/NordSecurity/uniffi-bindgen-cs/issues/75

Fix empty struct

---

bindgen/src/gen_cs/mod.rs
generate_bindings.sh
test_bindings.sh

Hi, this is a naive implementation to support osx, for what i can see on every other platform everything should stay the same and all tests now pass, let me know if there's something else i should do

Add support for OSX

---

bindgen/templates/ObjectTemplate.cs
dotnet-tests/UniffiCS.BindingTests/TestTraitMethod.cs

Hello! Thanks for maintaining this project, it's really been a lifesaver. 
I've implemented the `Eq` and `Hash` traits, skipping `Debug` because I'm not aware of a parallel in .NET. 
One caveat to note, if `Eq` is implemented but `Hash` is not, .NET will show a warning that `Object.GetHashCode()` should be overwritten as well. If they don't overwrite it, dictionaries/hashmaps and such might not work as expected.
We've been making heavy use of this crate at my org, and this contribution is really an attempt to get my feet wet in the repo with the hope of assisting with the async implementation. Any guidance/warnings on that front would be very appreciated. :)

Implement Eq and Hash trait methods

---

Cargo.lock
bindgen/src/gen_cs/mod.rs
bindgen/templates/Async.cs
bindgen/templates/Helpers.cs
bindgen/templates/ObjectRuntime.cs
bindgen/templates/ObjectTemplate.cs
bindgen/templates/TopLevelFunctionTemplate.cs
bindgen/templates/Types.cs
bindgen/templates/macros.cs
bindgen/templates/wrapper.cs
dotnet-tests/UniffiCS.BindingTests/OptionalParameterTests.cs
dotnet-tests/UniffiCS.BindingTests/TestCoverall.cs
dotnet-tests/UniffiCS.BindingTests/TestFutures.cs
fixtures/Cargo.toml
fixtures/src/lib.rs

Hello again, as promised I have made an attempt to implement async over the current `uniffi-rs` fork version. It seems to be working for our internal poc, so I thought it was a good time to contribute upstream and get some eyes on it. As discussed, rust pointers needed to be marshalled to `IntPtr` instead of `SafeHandle`. Performance seems to be ok, I stole the async tests from the `kristupas/async-0.24` branch and they pass most of the time, but can be flaky when they do not quite meet the tolerances. Let me know if I need to clarify anything, hope everyone had a great a holiday!

Async implementation

---

CONTRIBUTING.md
dotnet-tests/UniffiCS.BindingTests/CustomTestFramework.cs
dotnet-tests/UniffiCS.BindingTests/TestFutures.cs
dotnet-tests/UniffiCS.BindingTests/UniffiCS.BindingTests.csproj
dotnet-tests/UniffiCS.BindingTests/xunit.runner.json

By default, the tests are executed in parallel. While this doesn't seem to be causing any type of issues, it's quite counter intuitive for the type of tests implemented in this project. For example, some of the tests invoke GC and expect side effects from GC.
This commit also adds diagnostic messages to help to debug hanging tests. I implemented this after encountering a hanging test in one of Github PRs.

Execute tests in sequence

---

README.md
dotnet-tests/UniffiCS/UniffiCS.csproj

The generated bindings already support 4.6.1, update documentation and target framework version in test project settings.

Downgrade .NET framework target version 4.6.1

---

Cargo.lock
README.md
bindgen/templates/EnumTemplate.cs
bindgen/templates/ErrorTemplate.cs
bindgen/templates/macros.cs
dotnet-tests/UniffiCS.BindingTests/TestIssue60.cs
fixtures/Cargo.toml
fixtures/regressions/issue-60/Cargo.toml
fixtures/regressions/issue-60/README.md
fixtures/regressions/issue-60/src/lib.rs
fixtures/src/lib.rs

If associated enum class name matches it's parameter type name, prefix the parameter type with package namespace to restrict the compiler from picking the associated enum class instead of top level type definition
```
public record Rectangle(double @width, double @height) { }
public record Shape
{                    ____________
∨          ∧
public record Rectangle(Rectangle @s) : Shape { }
public record Ellipse(Ellipse @s) : Shape { }
}
```
```
namespace my_namespace;
public record Rectangle(double @width, double @height) { }
public record Shape ^_______________________
{                                           ^
public record Rectangle(my_namespace.Rectangle @s) : Shape { }
public record Ellipse(Ellipse @s) : Shape { }
}
```
Fixes …

Fix enums/errors case names shadowing parameters to top level type names

---

Cargo.lock
bindgen/src/gen_cs/filters.rs
bindgen/src/gen_cs/primitives.rs
dotnet-tests/UniffiCS.BindingTests/TestIssue110.cs
fixtures/Cargo.toml
fixtures/regressions/issue-110/Cargo.toml
fixtures/regressions/issue-110/README.md
fixtures/regressions/issue-110/build.rs
fixtures/regressions/issue-110/src/issue-110.udl
fixtures/regressions/issue-110/src/lib.rs
fixtures/src/lib.rs

This is done so that capitalized string types defined in the udl file are distinct from the builtin string type
Fixes #110

Use lower case string type

---

bindgen/src/lib.rs

I noticed that providing a config file is already supported in the code but prevented by the command line arguments validation. Removing that validation restriction allows me to successfully provide a config file.
fixes https://github.com/NordSecurity/uniffi-bindgen-cs/issues/119

Allow config file to be specified alongside --library

---

bindgen/templates/Helpers.cs

It should fix issue #128 
Considerations:
There's no reflection (especially not as heavy as "dynamic") minus very lightweight constructs (`is`) that are very fast.
This new implementation now supports all "IEnumerable" items to be deconstructed nicely, including but not limited to: Queue<T>, ConcurrentDictionary<K,V> and alike.
It also avoid calling to test "Dispose" when the collection is of primitive values.

Fixes heavy code on dispose.

---

.github/workflows/cs.yml
Dockerfile
docker.sh
dotnet-tests/UniffiCS.BindingTests/UniffiCS.BindingTests.csproj
dotnet-tests/UniffiCS/UniffiCS.csproj
rust-toolchain.toml

This PR updates the docker image used in CI:
- Update dotnet sdk to 9.0
- Bump rust version to 1.88

Update docker image to use sdk:9.0

---

bindgen/src/gen_cs/compounds.rs
bindgen/templates/BigEndianStream.cs
bindgen/templates/Helpers.cs
bindgen/templates/SequenceTemplate.cs
dotnet-tests/UniffiCS.BindingTests/TestCallbacksFixture.cs
dotnet-tests/UniffiCS.BindingTests/TestCoverall.cs
dotnet-tests/UniffiCS.BindingTests/TestErrorTypes.cs
dotnet-tests/UniffiCS.BindingTests/TestRondpoint.cs
dotnet-tests/UniffiCS.BindingTests/TestTodoList.cs
dotnet-tests/UniffiCS.BindingTests/TestTraits.cs

Reduces memory consumption, and most changes are "Count" (is the List's length) vs "Length" (array's one).
All tests are passing.
Fixes #137

Use sequence collection to be System.Array
